version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/clear_cache.sh
      runas: ubuntu

  AfterInstall:
    - location: scripts/composer_install.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/restart_apache.sh
      runas: root

